export const INITIALIZE_PROJECT = 'INITIALIZE_COLUMNS';
export const PROJECT_INITIALIZED = 'PROJECT_INITIALIZED';
export const FETCH_COLUMNS = 'FETCH_COLUMNS';
export const COLUMNS_FETCHED = 'COLUMNS_FETCHED';
export const ADD_COLUMN = 'ADD_COLUMN';
export const COLUMN_ADDED = 'COLUMN_ADDED';
